import React, { useState, useMemo, useRef } from 'react';
import { Compass, Sparkles, Target, Layers, Shield, Zap } from 'lucide-react';
import { PalaceCell, PalaceData, FlyingMutagenBadge } from './PalaceCell';
import { StarTag } from './StarTag';
import {
  getAnheIndex,
  getGridPosition,
} from '../data/palace-layout';

/** Direction vectors for roving-tabindex arrow key navigation on the 4x4 palace ring */
const ARROW_DELTA: Record<string, [number, number]> = {
  ArrowUp: [-1, 0],
  ArrowDown: [1, 0],
  ArrowLeft: [0, -1],
  ArrowRight: [0, 1],
};

/** Position (row,col) -> palace index lookup for the 12 outer palaces */
const POSITION_TO_INDEX = new Map<string, number>();
for (let i = 0; i < 12; i++) {
  const { row, col } = getGridPosition(i);
  POSITION_TO_INDEX.set(`${row},${col}`, i);
}

/** Find the next occupied palace stepping from `index` in direction (dRow, dCol), wrapping around the 4x4 grid */
function getNextPalaceIndex(index: number, dRow: number, dCol: number): number {
  let { row, col } = getGridPosition(index);
  for (let step = 0; step < 4; step++) {
    row = (row + dRow + 4) % 4;
    col = (col + dCol + 4) % 4;
    const next = POSITION_TO_INDEX.get(`${row},${col}`);
    if (next !== undefined) return next;
  }
  return index;
}
import {
  calculateFlyingStars,
  getPalaceMutagenLabels,
  type FlyingPalace,
  type FlyingStarsResult,
} from '../lib/flying';
import { canonicalizeFlyingPalaces, findSoulPalaceIndex, translateKey, type AppLocale } from '../lib/chartModel';
import { useTranslation } from '../i18n';

export interface ChartGridProps {
  /** Complete Astrolabe object generated by iztro or compatible chart object */
  astrolabe?: {
    solarDate?: string;
    lunarDate?: string;
    chineseDate?: string;
    fiveElementsClass?: string;
    soul?: string;
    body?: string;
    zodiac?: string;
    sign?: string;
    gender?: string;
    /** 命宮所在地支 (locale 無關，用於正確定位命宮預設選取) */
    earthlyBranchOfSoulPalace?: string;
    palaces: PalaceData[];
    surroundedPalaces: (targetIndex: number) => {
      target: PalaceData;
      opposite: PalaceData;
      wealth: PalaceData;
      career: PalaceData;
    };
  } | null;
  /** Selected palace index in controlled mode (0..11) */
  selectedIndex?: number;
  /** Callback fired when a palace cell is clicked */
  onSelectPalace?: (index: number) => void;
  className?: string;
}

export const ChartGrid: React.FC<ChartGridProps> = ({
  astrolabe,
  selectedIndex: propSelectedIndex,
  onSelectPalace,
  className = '',
}) => {
  const { t, locale } = useTranslation();
  const appLocale: AppLocale = locale === 'en' ? 'en' : 'zh-TW';

  // Find Life Palace default index (default to 0 if not found)
  // Root-cause C1 fix: match via locale-independent earthlyBranchOfSoulPalace,
  // not the Life Palace display string (fails outright when displaying in English).
  const defaultIndex = React.useMemo(() => {
    if (!astrolabe || !astrolabe.palaces || astrolabe.palaces.length === 0) return 0;
    return findSoulPalaceIndex(astrolabe as { palaces: Array<{ earthlyBranch: string }>; earthlyBranchOfSoulPalace?: string });
  }, [astrolabe]);

  const [internalSelectedIndex, setInternalSelectedIndex] = useState<number>(defaultIndex);

  // Reset to defaultIndex when new astrolabe is provided
  const [prevDefaultIndex, setPrevDefaultIndex] = useState(defaultIndex);
  if (defaultIndex !== prevDefaultIndex) {
    setPrevDefaultIndex(defaultIndex);
    setInternalSelectedIndex(defaultIndex);
  }

  // Selected palace index (controlled vs uncontrolled)
  const selectedIndex = propSelectedIndex !== undefined ? propSelectedIndex : internalSelectedIndex;

  // Calculate flying stars
  // 根因 C1 修復：無論 astrolabe 是以哪種顯示語言排盤，先轉換回 zh-TW canonical
  // key 再交給 calculateFlyingStars (其內部 MUTAGEN_TABLE 以繁體中文為 key)，
  // 確保英文模式下飛星四化計算依然正確。
  const flyingResult: FlyingStarsResult | null = useMemo(() => {
    if (!astrolabe || !astrolabe.palaces || astrolabe.palaces.length !== 12) return null;
    const rawFlyingPalaces: FlyingPalace[] = astrolabe.palaces.map((p) => ({
      index: p.index,
      name: p.name,
      heavenlyStem: p.heavenlyStem,
      earthlyBranch: p.earthlyBranch,
      majorStars: p.majorStars.map((s) => ({ name: s.name, mutagen: s.mutagen })),
      minorStars: p.minorStars.map((s) => ({ name: s.name, mutagen: s.mutagen })),
    }));
    const canonicalFlyingPalaces = canonicalizeFlyingPalaces(rawFlyingPalaces, appLocale) as FlyingPalace[];
    return calculateFlyingStars(canonicalFlyingPalaces);
  }, [astrolabe, appLocale]);

  const handleCellClick = (index: number) => {
    setInternalSelectedIndex(index);
    if (onSelectPalace) {
      onSelectPalace(index);
    }
  };

  const cellRefs = useRef<Array<HTMLButtonElement | null>>([]);

  const handleCellKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>, index: number) => {
    let nextIndex: number | null = null;
    const delta = ARROW_DELTA[event.key];
    if (delta) {
      nextIndex = getNextPalaceIndex(index, delta[0], delta[1]);
    } else if (event.key === 'Home') {
      nextIndex = 0;
    } else if (event.key === 'End') {
      nextIndex = 11;
    }
    if (nextIndex === null) return;
    event.preventDefault();
    handleCellClick(nextIndex);
    cellRefs.current[nextIndex]?.focus();
  };

  if (!astrolabe || !astrolabe.palaces || astrolabe.palaces.length !== 12) {
    return (
      <div className="glass-panel p-8 rounded-2xl border border-slate-200 dark:border-slate-800 flex flex-col items-center justify-center min-h-[400px] text-center space-y-4">
        <div className="p-4 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-500 dark:text-amber-400">
          <Compass className="w-10 h-10 animate-spin-slow" />
        </div>
        <h3 className="text-lg font-bold text-slate-800 dark:text-slate-200">{t('chart.empty')}</h3>
        <p className="text-sm text-slate-600 dark:text-slate-400 max-w-md">
          {t('chart.emptyHint')}
        </p>
      </div>
    );
  }

  const { palaces } = astrolabe;

  // Calculate surrounding and anhe palace indices using iztro API
  const sanfang = astrolabe.surroundedPalaces(selectedIndex);
  const anheIdx = getAnheIndex(selectedIndex);

  // Selected palace data
  const selectedPalace = sanfang.target;
  const oppositePalace = sanfang.opposite;
  const careerPalace = sanfang.career;
  const wealthPalace = sanfang.wealth;
  const anhePalace = palaces[anheIdx];

  // Determine palace role relative to selectedIndex
  const getPalaceRole = (index: number) => {
    if (index === sanfang.target.index) return 'target';
    if (index === sanfang.opposite.index) return 'opposite';
    if (index === sanfang.career.index) return 'career';
    if (index === sanfang.wealth.index) return 'wealth';
    if (index === anheIdx) return 'anhe';
    return null;
  };

  // Get flying star badges for a palace cell
  // flyingResult 內部一律是 zh-TW canonical key，這裡轉回目前顯示語言供渲染
  const getFlyingBadges = (index: number): FlyingMutagenBadge[] => {
    if (!flyingResult) return [];
    const labels = getPalaceMutagenLabels(index, flyingResult);
    return labels.map((l) => ({
      star: translateKey(l.star, 'star', appLocale),
      type: l.type,
      source: l.source,
      fromPalace: l.fromPalace ? translateKey(l.fromPalace, 'palace', appLocale) : l.fromPalace,
    }));
  };

  // Get flying star details for selected palace
  const getSelectedFlyingDetail = () => {
    if (!flyingResult) return null;
    return flyingResult.palaces[selectedIndex] ?? null;
  };

  const selectedFlyingDetail = getSelectedFlyingDetail();

  return (
    <div className={`space-y-6 ${className}`}>
      {/* 4x4 Palace Grid */}
      <div role="region" aria-label={t('a11y.chartGrid')} className="grid grid-cols-4 grid-rows-4 gap-2 aspect-square w-full max-w-[800px] mx-auto p-3 bg-slate-100/90 dark:bg-slate-950/80 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-2xl relative">
        {/* Outer 12 Palaces */}
        {palaces.map((palace, index) => {
          const { row, col } = getGridPosition(index);
          const role = getPalaceRole(index);
          const isSelected = index === selectedIndex;
          const flyingBadges = getFlyingBadges(index);

          return (
            <div
              key={`palace-grid-${index}-${palace.earthlyBranch}`}
              style={{
                gridRowStart: row + 1,
                gridColumnStart: col + 1,
              }}
            >
              <PalaceCell
                ref={(el) => { cellRefs.current[index] = el; }}
                palace={palace}
                isSelected={isSelected}
                role={role}
                flyingBadges={flyingBadges}
                tabIndex={index === selectedIndex ? 0 : -1}
                onClick={() => handleCellClick(index)}
                onKeyDown={(e) => handleCellKeyDown(e, index)}
              />
            </div>
          );
        })}

        {/* Center 2x2 Header (Grid Row 2..3, Col 2..3) */}
        <div
          className="bg-white/90 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-700/60 rounded-xl p-4 flex flex-col justify-between overflow-hidden shadow-inner backdrop-blur-md"
          style={{
            gridRow: '2 / span 2',
            gridColumn: '2 / span 2',
          }}
        >
          {/* Center Info Header */}
          <div className="border-b border-slate-200 dark:border-slate-800 pb-2 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-amber-500/20 text-amber-500 dark:text-amber-400">
                <Compass className="w-4 h-4" aria-hidden="true" />
              </div>
              <div>
                <h4 className="text-sm font-bold text-amber-700 dark:text-amber-200">{t('chart.center')}</h4>
                <p className="text-[10px] text-slate-500 dark:text-slate-400 font-mono">
                  {astrolabe.gender === 'female' ? t('form.female') : t('form.male')} · {astrolabe.fiveElementsClass || t('chart.fiveElementsDefault')}
                </p>
              </div>
            </div>
            {selectedPalace && (
              <span className="px-2 py-0.5 rounded-full text-xs font-bold bg-amber-500/20 text-amber-800 dark:text-amber-300 border border-amber-500/40">
                {selectedPalace.heavenlyStem}{selectedPalace.earthlyBranch} · {selectedPalace.name}
              </span>
            )}
          </div>

          {/* Basic Astrolabe Parameters */}
          <div className="grid grid-cols-2 gap-2 my-2 text-xs">
            <div className="bg-slate-50 dark:bg-slate-950/50 p-2 rounded-lg border border-slate-200 dark:border-slate-800/80">
              <span className="text-[10px] text-slate-500 dark:text-slate-400 block">{t('chart.solarBirthday')}</span>
              <span className="font-mono text-slate-800 dark:text-slate-200 font-medium truncate block">
                {astrolabe.solarDate || '—'}
              </span>
            </div>
            <div className="bg-slate-50 dark:bg-slate-950/50 p-2 rounded-lg border border-slate-200 dark:border-slate-800/80">
              <span className="text-[10px] text-slate-500 dark:text-slate-400 block">{t('chart.lunarBirthday')}</span>
              <span className="font-mono text-slate-800 dark:text-slate-200 font-medium truncate block">
                {astrolabe.lunarDate || '—'}
              </span>
            </div>
            <div className="bg-slate-50 dark:bg-slate-950/50 p-2 rounded-lg border border-slate-200 dark:border-slate-800/80">
              <span className="text-[10px] text-slate-500 dark:text-slate-400 block">{t('chart.soulBody')}</span>
              <span className="text-amber-700 dark:text-amber-300 font-semibold truncate block">
                {astrolabe.soul || '—'} / {astrolabe.body || '—'}
              </span>
            </div>
            <div className="bg-slate-50 dark:bg-slate-950/50 p-2 rounded-lg border border-slate-200 dark:border-slate-800/80">
              <span className="text-[10px] text-slate-500 dark:text-slate-400 block">{t('chart.zodiacSign')}</span>
              <span className="text-slate-800 dark:text-slate-200 font-medium truncate block">
                {astrolabe.zodiac || '—'} / {astrolabe.sign || '—'}
              </span>
            </div>
          </div>

          {/* Sanfang Sizheng & Anhe Quick View */}
          {selectedPalace && (
            <div className="border-t border-slate-200 dark:border-slate-800 pt-2 text-xs space-y-1.5">
              <div className="flex items-center justify-between text-[11px] text-slate-500 dark:text-slate-400 font-medium">
                <span className="flex items-center gap-1">
                  <Target className="w-3 h-3 text-amber-500 dark:text-amber-400" aria-hidden="true" />
                  {t('chart.sanfang')}
                </span>
                <span className="text-[10px] text-slate-600 dark:text-slate-400">{t('chart.clickHint')}</span>
              </div>
              <div className="grid grid-cols-2 gap-1.5 text-[11px]">
                <div className="bg-rose-50 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-500/30 rounded p-1.5 flex items-center justify-between text-rose-800 dark:text-rose-200">
                  <span className="font-semibold text-rose-600 dark:text-rose-400">{t('chart.opposite')}:</span>
                  <span>
                    {oppositePalace.heavenlyStem}{oppositePalace.earthlyBranch} · {oppositePalace.name}
                  </span>
                </div>
                <div className="bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-500/30 rounded p-1.5 flex items-center justify-between text-emerald-800 dark:text-emerald-200">
                  <span className="font-semibold text-emerald-600 dark:text-emerald-400">{t('chart.anhe')}:</span>
                  <span>
                    {anhePalace.heavenlyStem}{anhePalace.earthlyBranch} · {anhePalace.name}
                  </span>
                </div>
                <div className="bg-sky-50 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-500/30 rounded p-1.5 flex items-center justify-between text-sky-800 dark:text-sky-200">
                  <span className="font-semibold text-sky-600 dark:text-sky-400">{t('chart.career')}:</span>
                  <span>
                    {careerPalace.heavenlyStem}{careerPalace.earthlyBranch} · {careerPalace.name}
                  </span>
                </div>
                <div className="bg-cyan-50 dark:bg-cyan-950/30 border border-cyan-200 dark:border-cyan-500/30 rounded p-1.5 flex items-center justify-between text-cyan-800 dark:text-cyan-200">
                  <span className="font-semibold text-cyan-600 dark:text-cyan-400">{t('chart.wealth')}:</span>
                  <span>
                    {wealthPalace.heavenlyStem}{wealthPalace.earthlyBranch} · {wealthPalace.name}
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Selected Palace Detail Panel */}
      {selectedPalace && (
        <div className="glass-panel p-6 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-4">
          <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-amber-500/20 text-amber-800 dark:text-amber-300 font-bold font-mono">
                {selectedPalace.heavenlyStem}{selectedPalace.earthlyBranch}
              </div>
              <div>
                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                  【{selectedPalace.name}】{t('chart.detailPanel')}
                  {selectedPalace.isBodyPalace && (
                    <span className="px-2 py-0.5 rounded text-xs bg-purple-500/20 dark:bg-purple-500/30 text-purple-700 dark:text-purple-300 border border-purple-500/50">
                      {t('chart.bodyPalace')}
                    </span>
                  )}
                  {selectedPalace.isOriginalPalace && (
                    <span className="px-2 py-0.5 rounded text-xs bg-amber-500/20 dark:bg-amber-500/30 text-amber-800 dark:text-amber-300 border border-amber-500/50">
                      {t('chart.originPalace')}
                    </span>
                  )}
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  {t('chart.decadal')}：{selectedPalace.decadal?.range ? `${selectedPalace.decadal.range[0]} - ${selectedPalace.decadal.range[1]} ${t('fortune.ageUnit')}` : '—'}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <span className="text-xs px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
                {t('chart.earthBranch')}：{selectedPalace.earthlyBranch}{t('fortune.gong')} ({t('chart.position')} {selectedIndex})
              </span>
            </div>
          </div>

          {/* Palace Star Group Details */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Major Stars */}
            <div className="bg-white/80 dark:bg-slate-900/80 p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-2">
              <h4 className="text-xs font-bold text-amber-600 dark:text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" aria-hidden="true" />
                {t('chart.majorStars')}
              </h4>
              <div className="flex flex-wrap gap-2 pt-1">
                {selectedPalace.majorStars.length > 0 ? (
                  selectedPalace.majorStars.map((star, i) => (
                    <StarTag
                      key={`detail-major-${i}`}
                      name={star.name}
                      brightness={star.brightness}
                      mutagen={star.mutagen}
                      type="major"
                      vertical={false}
                    />
                  ))
                ) : (
                  <span className="text-xs text-slate-400 dark:text-slate-500">{t('chart.emptyPalace', { name: oppositePalace.name })}</span>
                )}
              </div>
            </div>

            {/* Auxiliary Stars */}
            <div className="bg-white/80 dark:bg-slate-900/80 p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-2">
              <h4 className="text-xs font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5" aria-hidden="true" />
                {t('chart.minorStars')}
              </h4>
              <div className="flex flex-wrap gap-2 pt-1">
                {selectedPalace.minorStars.length > 0 ? (
                  selectedPalace.minorStars.map((star, i) => (
                    <StarTag
                      key={`detail-minor-${i}`}
                      name={star.name}
                      brightness={star.brightness}
                      mutagen={star.mutagen}
                      type="minor"
                      vertical={false}
                    />
                  ))
                ) : (
                  <span className="text-xs text-slate-400 dark:text-slate-500">{t('chart.noMinor')}</span>
                )}
              </div>
            </div>

            {/* Minor Stars & Spirits */}
            <div className="bg-white/80 dark:bg-slate-900/80 p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-2">
              <h4 className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
                <Layers className="w-3.5 h-3.5" aria-hidden="true" />
                {t('chart.adjectiveStars')}
              </h4>
              <div className="flex flex-wrap gap-1.5 pt-1">
                {selectedPalace.adjectiveStars.length > 0 ? (
                  selectedPalace.adjectiveStars.map((star, i) => (
                    <span
                      key={`detail-adj-${i}`}
                      className="px-1.5 py-0.5 rounded text-xs bg-slate-100 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/50 text-slate-700 dark:text-slate-300"
                    >
                      {star.name}
                    </span>
                  ))
                ) : (
                  <span className="text-xs text-slate-400 dark:text-slate-500">{t('chart.noAdj')}</span>
                )}
              </div>
            </div>
          </div>

          {/* Flying Star Mutagen Details */}
          {selectedFlyingDetail && (
            <div className="bg-white/80 dark:bg-slate-900/80 p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-3">
              <h4 className="text-xs font-bold text-violet-600 dark:text-violet-400 uppercase tracking-wider flex items-center gap-1.5">
                <Zap className="w-3.5 h-3.5" aria-hidden="true" />
                {t('chart.flying')} ({t('chart.stemLabel')}：{translateKey(selectedFlyingDetail.heavenlyStem, 'stem', appLocale)})
              </h4>

              {/* Fly Out */}
              <div className="space-y-1.5">
                <p className="text-[10px] text-slate-500 dark:text-slate-400 font-medium">▸ {t('chart.flyOut')}</p>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5">
                  {selectedFlyingDetail.flyingOut.map((fly, i) => (
                    <div
                      key={`out-${i}`}
                      className={`px-2 py-1 rounded text-[11px] border ${
                        fly.targetPalaceIndex === selectedIndex
                          ? 'bg-amber-500/15 border-amber-500/40 text-amber-900 dark:text-amber-200'
                          : 'bg-slate-100 dark:bg-slate-800/50 border-slate-200 dark:border-slate-700/50 text-slate-700 dark:text-slate-300'
                      }`}
                    >
                      <span className="font-bold">{translateKey(fly.star, 'star', appLocale)}</span>
                      <span className="text-slate-600 dark:text-slate-400"> {t('chart.hua')}</span>
                      <span className={`font-bold ${
                        fly.type === '\u797f' ? 'text-emerald-600 dark:text-emerald-400' :
                        fly.type === '\u6b0a' ? 'text-rose-600 dark:text-rose-400' :
                        fly.type === '\u79d1' ? 'text-sky-600 dark:text-sky-400' :
                        'text-purple-600 dark:text-purple-400'
                      }`}>{translateKey(fly.type, 'mutagen', appLocale)}</span>
                      <span className="text-slate-400 dark:text-slate-500 text-[10px]"> → {translateKey(fly.targetPalaceName, 'palace', appLocale)}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Fly In */}
              {selectedFlyingDetail.flyingIn.length > 0 && (
                <div className="space-y-1.5">
                  <p className="text-[10px] text-slate-500 dark:text-slate-400 font-medium">▸ {t('chart.flyIn')}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {selectedFlyingDetail.flyingIn.map((fly, i) => (
                      <div
                        key={`in-${i}`}
                        className="px-2 py-1 rounded text-[11px] border border-dashed bg-slate-100/50 dark:bg-slate-800/30 border-slate-300 dark:border-slate-600/50 text-slate-700 dark:text-slate-300"
                      >
                        <span className="font-bold">{translateKey(fly.star, 'star', appLocale)}</span>
                        <span className="text-slate-600 dark:text-slate-400"> {t('chart.hua')}</span>
                        <span className={`font-bold ${
                          fly.type === '\u797f' ? 'text-emerald-600 dark:text-emerald-400' :
                          fly.type === '\u6b0a' ? 'text-rose-600 dark:text-rose-400' :
                          fly.type === '\u79d1' ? 'text-sky-600 dark:text-sky-400' :
                          'text-purple-600 dark:text-purple-400'
                        }`}>{translateKey(fly.type, 'mutagen', appLocale)}</span>
                        <span className="text-slate-400 dark:text-slate-500 text-[10px]"> ← {translateKey(fly.sourcePalaceName, 'palace', appLocale)}({translateKey(fly.sourceStem, 'stem', appLocale)})</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
